name = "oscars-pool"
main = "src/index.js"
compatibility_date = "2024-02-08"
node_compat = true
# I'm not clear on the recommended pattern by Cloudflare
# They want the wrangler.toml file to be the source of truth https://developers.cloudflare.com/workers/wrangler/configuration/#source-of-truth
# but that would mean committing production secrets here.
# Need to look more into their recommended pattern, but for now this is fine.
# The production PostgresSQL connection URL is in dash.cloudflare.com
keep_vars = true

[vars]
DB_URL = "postgres://postgres:postgres@localhost/local"

[dev]
port = 8345
