name = "workers-backend"
main = "src/index.js"
compatibility_date = "2024-02-08"
node_compat = true

[vars]
DB_URL = "postgres://postgres:postgres@localhost/local"

[dev]
port = 8345
#ip = "192.168.1.1"
#local_protocol = "http"
